// VGA_video_pll_0.v

// This file was auto-generated from altera_up_avalon_video_pll_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 20.1 720

`timescale 1 ps / 1 ps
module VGA_video_pll_0 (
	);

endmodule
